version: "3.9"
services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: restornew_app
      MYSQL_USER: restornew_app
      MYSQL_PASSWORD: "i*2ubUF7LOaG"
      MYSQL_ROOT_PASSWORD: "i*2ubUF7LOaG"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: ["mysqld", "--mysql-native-password=ON"]
volumes:
  mysql-data:
